/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
	kotlin("jvm") version "1.9.20"
	id("io.gitlab.arturbosch.detekt").version("1.23.3")
}

repositories {
	mavenCentral()
	maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
	google()
}

kotlin {
	jvmToolchain(17)
}

val reportMerge by tasks.registering(io.gitlab.arturbosch.detekt.report.ReportMergeTask::class) {
	output.set(rootProject.layout.buildDirectory.file("reports/detekt/merge.sarif"))
}

subprojects {
	apply(plugin = "io.gitlab.arturbosch.detekt")

	tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
		finalizedBy(reportMerge)
	}

	reportMerge {
		input.from(tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().map { it.sarifReportFile })
	}
}
