/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
	kotlin("jvm") version "1.9.20"
	id("io.gitlab.arturbosch.detekt").version("1.23.3")
}

repositories {
	mavenCentral()
	maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
	google()
}

dependencies {
	testImplementation("org.jetbrains.kotlin:kotlin-test")
}

kotlin {
	jvmToolchain(21)
}
